ValueError('Invalid limits given: (((k, 4, 4), (d, 6, 4)),)',)
