ValueError('Invalid limits given: (((z, 2, 2), (k, 9, 9)),)',)
